name: Run Daily Script

on:
  schedule:
    - cron: '6 21 * * *'   # runs every day at 20:59 UTC
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Replace tokens in JSON
        uses: cschleiden/replace-tokens@v1
        with:
          files: 'config.json'
          tokenPrefix: '{{'
          tokenSuffix: '}}'
        env:
          SECRET_API_KEY: ${{ secrets.DISCORD_TOKEN }}

      - name: Show updated config
        run: cat config.json
        
      - name: Run autoTriggerShop
        env:
          DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
          USER_ID: "1248529349443846154"
          CHANNEL_ID: "1264023343577694372"
          RIOT_ID: ${{ secrets.RIOT_ID }}
        run: node autoTriggerShop.js
